# Stage 1 ( # Use an official Node runtime as the base image) it uses slim image for reduced image size
From node:18-slim
 
# Set the working directory for the container
WORKDIR /app
 
# Copy data from required pacakges into the container
COPY package*.json ./
 
# Install app dependencies
RUN npm install
 
# Copy the rest of the application code
COPY . .
 
# Exposes the port number 3000 to run the application on port 3000
EXPOSE 3000
 
# Specify the command to run your application
CMD ["npm", "run", "dev"]
